# Generated by Django 4.2.16 on 2024-10-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApplication', '0003_rename_sexe_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalbox',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalbox',
            name='code',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
