# Generated by Django 4.2.16 on 2024-10-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApplication', '0005_alter_patient_email_alter_patient_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phoneNumber',
            field=models.CharField(max_length=20),
        ),
    ]
