# Generated by Django 4.2.16 on 2024-10-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApplication', '0006_alter_patient_email_alter_patient_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalbox',
            name='weight',
            field=models.FloatField(max_length=10),
        ),
    ]
