# Generated by Django 4.2.16 on 2024-10-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApplication', '0007_alter_medicalbox_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalbox',
            name='code',
        ),
        migrations.AddField(
            model_name='medicalbox',
            name='address',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalbox',
            name='hours',
            field=models.ManyToManyField(related_name='boxes', to='webApplication.hourmedication'),
        ),
    ]
