# Generated by Django 4.2.16 on 2024-10-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApplication', '0008_hourmedication_remove_medicalbox_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalbox',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
