# Generated by Django 4.2.16 on 2024-10-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApplication', '0009_alter_medicalbox_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalbox',
            name='address',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
