# Generated by Django 5.1.2 on 2024-11-26 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApplication', '0011_datamedication'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='datamedication',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webApplication.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourmedication',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webApplication.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalbox',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webApplication.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webApplication.user'),
            preserve_default=False,
        ),
    ]
