# Generated by Django 5.1.2 on 2024-11-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApplication', '0012_user_datamedication_user_hourmedication_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='username',
        ),
    ]
