# Generated by Django 5.1.2 on 2024-11-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApplication', '0014_alter_datamedication_user_alter_medicalbox_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamedication',
            name='user',
        ),
    ]
